apiVersion: v1
kind: Secret
metadata:
  name: kubepilot-secrets
  namespace: kubepilot-system
stringData:
  jwt_secret: kubepilot_super_secret_enterprise_key_2026
  postgres_password: kubepilot_secret
  postgres_user: kubepilot
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: kubepilot-secrets
  namespace: kubepilot-apps
stringData:
  jwt_secret: kubepilot_super_secret_enterprise_key_2026
  postgres_password: kubepilot_secret
  postgres_user: kubepilot
type: Opaque
