apiVersion: v1
kind: Secret
metadata:
  name: kubepilot-secrets
  namespace: kubepilot-system
stringData:
  jwt-secret: kubepilot_super_secret_enterprise_key_2026
  postgres-password: kubepilot_secret
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: kubepilot-secrets
  namespace: kubepilot-apps
stringData:
  jwt-secret: kubepilot_super_secret_enterprise_key_2026
  postgres-password: kubepilot_secret
type: Opaque
