apiVersion: v1
data:
  ENVIRONMENT: production
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector.kubepilot-observability.svc.cluster.local:4317
  POSTGRES_DB: kubepilot_db
  POSTGRES_HOST: postgres-db.kubepilot-system.svc.cluster.local
  POSTGRES_PORT: '5432'
  REDIS_HOST: redis-master.kubepilot-system.svc.cluster.local
  REDIS_PORT: '6379'
kind: ConfigMap
metadata:
  name: kubepilot-global-config
  namespace: kubepilot-system
---
apiVersion: v1
data:
  ENVIRONMENT: production
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector.kubepilot-observability.svc.cluster.local:4317
  POSTGRES_DB: kubepilot_db
  POSTGRES_HOST: postgres-db.kubepilot-system.svc.cluster.local
  POSTGRES_PORT: '5432'
  REDIS_HOST: redis-master.kubepilot-system.svc.cluster.local
  REDIS_PORT: '6379'
kind: ConfigMap
metadata:
  name: kubepilot-global-config
  namespace: kubepilot-apps
