apiVersion: v1
data:
  nginx.conf: "events {\n    worker_connections 1024;\n}\nhttp {\n    upstream auth_service\
    \ {\n        server auth-service.kubepilot-apps.svc.cluster.local:8001;\n    }\n\
    \    upstream payment_service {\n        server payment-service.kubepilot-apps.svc.cluster.local:8002;\n\
    \    }\n    server {\n        listen 80;\n        server_name _;\n\n        location\
    \ /auth/ {\n            proxy_pass http://auth_service/;\n            proxy_set_header\
    \ Host $host;\n        }\n        location /payment/ {\n            proxy_pass\
    \ http://payment_service/;\n            proxy_set_header Host $host;\n       \
    \ }\n        location /health {\n            return 200 '{\"status\":\"ok\", \"\
    service\":\"api-gateway\"}';\n            add_header Content-Type application/json;\n\
    \        }\n    }\n}\n"
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: kubepilot-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: kubepilot-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - image: nginx:1.25-alpine
        imagePullPolicy: Never
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        name: nginx
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: config-volume
          subPath: nginx.conf
      volumes:
      - configMap:
          name: api-gateway-config
        name: config-volume
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: kubepilot-system
spec:
  ports:
  - nodePort: 30080
    port: 80
    targetPort: 80
  selector:
    app: api-gateway
  type: NodePort
