apiVersion: v1
kind: Secret
metadata:
  name: kubepilot-secrets
  namespace: kubepilot-system
type: Opaque
stringData:
  jwt-secret: "kubepilot_super_secret_enterprise_key_2026"
  postgres-password: "kubepilot_secret"
---
apiVersion: v1
kind: Secret
metadata:
  name: kubepilot-secrets
  namespace: kubepilot-apps
type: Opaque
stringData:
  jwt-secret: "kubepilot_super_secret_enterprise_key_2026"
  postgres-password: "kubepilot_secret"
